/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Docs: () => import('#controllers/docs_controller'),
  Home: () => import('#controllers/home_controller'),
}
